
./msg
        Received request from 127.0.0.1
        GET / HTTP/1.1
        Host: localhost:8000
        User-Agent: curl/8.7.1
        Accept: */*
./msg
        Received request from 127.0.0.1
        GET / HTTP/1.1
        Host: localhost:8000
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
./msg
        Received request from 127.0.0.1
        GET / HTTP/1.1
        Host: localhost:8000
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
./msg
        Received request from 127.0.0.1
        GET / HTTP/1.1
        Host: localhost:8000
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
./msg
        Received request from 127.0.0.1
        GET / HTTP/1.1
        Host: localhost:8000
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
./msg
        Received request from 127.0.0.1
        GET / HTTP/1.1
        Host: localhost:8000
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
